python train_quest_sft.py --config-name=train_prior.yaml \
    task=libero_90 \
    algo=quest \
    exp_name=final_base \
    variant_name=block_32_ds_4_ours \
    training.use_tqdm=true \
    training.save_all_checkpoints=true \
    training.use_amp=false \
    train_dataloader.persistent_workers=true \
    train_dataloader.num_workers=6 \
    make_unique_experiment_dir=true \
    algo.skill_block_size=32 \
    algo.downsample_factor=4 \
    training.auto_continue=false \
    rollout.num_parallel_envs=5 \
    rollout.rollouts_per_env=5 \
    checkpoint_path=FILL_IN_YOUR_CHECKPOINT_PATH_FROM_STAGE_1 \
    seed=0