defaults:
  - train_base
  - override task: libero_object
  - _self_

stage: 1 # 0 - pretrain autoencoder, 1 - train multitask, 2 - finetune multitask

logging_folder: prior

training:
  n_epochs: 200

rollout:
  interval: 25 # 25 is best for libero, 10 for metaworld
  rollouts_per_env: 5
  num_parallel_envs: 5 # 5 recommended for libero, 1 for metaworld