defaults:
  - train_base_rl_pi0_cfg
  - _self_
  - override task: libero_goal_rl
  - override reward_function: success

exp_name: pi0_cfg_all_task_goal

task:
  task_names_to_use: null

algo:
  # 适中开销的全任务训练参数（可按需覆盖）
  rollouts_per_env: 50
  num_parallel_envs: 10

training:
  n_steps: 12
  rollout_steps: 4
  log_interval: 1
  save_interval: 1

rollout:
  enabled: true
  interval: 4


