defaults:
  - train_base_rl_pi0_cfg
  - _self_
  - override task: libero_goal_rl
  - override reward_function: success

exp_name: pi0_cfg_all_task_goal

task:
  task_names_to_use: null

algo:
  rollouts_per_env: 16
  num_parallel_envs: 1

training:
  n_steps: 50000
  rollout_steps: 2000
  log_interval: 100
  save_interval: 5000

rollout:
  enabled: true
  interval: 2000


